/**
 * This class is generated by jOOQ
 */
package de.rwth.dbis.acis.activitytracker.service.dal.jooq;


import de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.Activity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Activitytracker extends SchemaImpl {

	private static final long serialVersionUID = -1305086332;

	/**
	 * The reference instance of <code>activitytracker</code>
	 */
	public static final Activitytracker ACTIVITYTRACKER = new Activitytracker();

	/**
	 * No further instances allowed
	 */
	private Activitytracker() {
		super("activitytracker");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Activity.ACTIVITY);
	}
}
