/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.activitytracker.service.dal.jooq;


import de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.Activity;
import de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reqbaztrack extends SchemaImpl {

    private static final long serialVersionUID = -2136063656;

    /**
     * The reference instance of <code>reqbaztrack</code>
     */
    public static final Reqbaztrack REQBAZTRACK = new Reqbaztrack();

    /**
     * The table <code>reqbaztrack.activity</code>.
     */
    public final Activity ACTIVITY = de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.Activity.ACTIVITY;

    /**
     * The table <code>reqbaztrack.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Reqbaztrack() {
        super("reqbaztrack", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Activity.ACTIVITY,
            SchemaVersion.SCHEMA_VERSION);
    }
}
