/*
 * This file is generated by jOOQ.
*/
package de.rwth.dbis.acis.activitytracker.service.dal.jooq;


import de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.Activity;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in reqbaztrack
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>reqbaztrack.activity</code>.
     */
    public static final Activity ACTIVITY = de.rwth.dbis.acis.activitytracker.service.dal.jooq.tables.Activity.ACTIVITY;
}
